Full Arithmetics topic tasks
Chernousovs/06-2021 pull request #2
Opened 2021-11-29 14:21 UTC by Chernousovs

2021-11-29 19:49 UTC, ausmoons requested changes

2021-11-29 19:49 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/ConsoleApp1/Geometry.cs
> +        }
Starp metodēm ir vajadzīga tukša rinda

2021-11-29 19:49 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/ConsoleApp1/Program.cs
> +        private static void CalcRectArea()
Labāk lietot pilno vārdu, nevis šādu saīsinājumu. Tikai dažu burtu atšķirība

2021-11-29 19:49 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/ConsoleApp1/Program.cs
> +
Lieka tukša rinda

2021-11-29 19:49 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/ConsoleApp1/Program.cs
> +
Liekas tukšas rindas

2021-11-29 19:49 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise1/Program.cs
> +            else if (firstNumber + secondNumber == 15)
Vienādos if var likt kopā. Un kur ir dalīšana, reizināšana?

2021-11-29 19:49 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise5/Program.cs
> +            else if (guess > num)
šis var būt else, jo citas iespējas vairs nav

2021-11-29 19:49 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise9/Program.cs
> +                Console.WriteLine($"BMI is {bmi}, you have underweight.");
Kur būs 18.5 un 25?

2021-11-30 10:04 UTC, Chernousovs commented on csharp-basics/exercises/Arithmetic/Exercise1/Program.cs
> +            else if (firstNumber + secondNumber == 15)
Pievienoju starpību.

2021-11-30 10:06 UTC, Chernousovs commented on csharp-basics/exercises/Arithmetic/Exercise9/Program.cs
> +                Console.WriteLine($"BMI is {bmi}, you have underweight.");
17. if (bmi <= 25 && bmi >= 18.5)
Ta izlabots, bet status nav "outdated", vai varu spiest "Resolve conversation"

2021-11-30 10:07 UTC, Chernousovs commented on csharp-basics/exercises/Arithmetic/ConsoleApp1/Geometry.cs
> +        }
Izlabots, bet status nav "outdated", vai varu spiest "Resolve conversation"

2021-12-01 16:35 UTC, ausmoons approved these changes

2021-12-01 22:04 UTC, merged